//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUGUACSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BolsaLaboralCarrera
    {
        public long IDBolsaLaboralCarrera { get; set; }
        public long IDBolsaLaboral { get; set; }
        public string IDCarreraProfesional { get; set; }
    
        public virtual BolsaLaboral BolsaLaboral { get; set; }
        public virtual EscuelaProfesional EscuelaProfesional { get; set; }
    }
}
