//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUGUACSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPMiembro
    {
        public long IDCPMiembro { get; set; }
        public string IDCarreraProfesional { get; set; }
        public string DNI { get; set; }
    
        public virtual Miembro Miembro { get; set; }
        public virtual EscuelaProfesional EscuelaProfesional { get; set; }
    }
}
