//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUGUACSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscuelaProfesional
    {
        public EscuelaProfesional()
        {
            this.BolsaLaboralCarrera = new HashSet<BolsaLaboralCarrera>();
            this.EPMiembro = new HashSet<EPMiembro>();
        }
    
        public string IDCarreraProfesional { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<BolsaLaboralCarrera> BolsaLaboralCarrera { get; set; }
        public virtual ICollection<EPMiembro> EPMiembro { get; set; }
    }
}
