//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUGUACSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membresia
    {
        public Membresia()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public long IDMembresia { get; set; }
        public string IDAsociado { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Tipo { get; set; }
        public string CategoriaMembresia { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
