//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUGUACSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembro
    {
        public Miembro()
        {
            this.EPMiembro = new HashSet<EPMiembro>();
        }
    
        public string DNI { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string Celular { get; set; }
        public string Telefonopcional { get; set; }
        public string Direccion { get; set; }
        public string CorreoElectronico { get; set; }
    
        public virtual ICollection<EPMiembro> EPMiembro { get; set; }
    }
}
