//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUGUACSystem.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ASUGUACEntities : DbContext
    {
        public ASUGUACEntities()
            : base("name=ASUGUACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actividad> Actividad { get; set; }
        public DbSet<BolsaLaboral> BolsaLaboral { get; set; }
        public DbSet<BolsaLaboralCarrera> BolsaLaboralCarrera { get; set; }
        public DbSet<Busqueda> Busqueda { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<EPMiembro> EPMiembro { get; set; }
        public DbSet<EscuelaProfesional> EscuelaProfesional { get; set; }
        public DbSet<Membresia> Membresia { get; set; }
        public DbSet<Miembro> Miembro { get; set; }
        public DbSet<Notificacion> Notificacion { get; set; }
        public DbSet<Promocion> Promocion { get; set; }
        public DbSet<Publicacion> Publicacion { get; set; }
        public DbSet<Sesion> Sesion { get; set; }
        public DbSet<Solicitud> Solicitud { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tag> Tag { get; set; }
        public DbSet<TipoActividad> TipoActividad { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    
        public virtual int Actividad_Create(string nombre, string descripcion, Nullable<long> iDTipoActividad, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string estado, string iDUsuario, ObjectParameter iDActividad)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var iDTipoActividadParameter = iDTipoActividad.HasValue ?
                new ObjectParameter("IDTipoActividad", iDTipoActividad) :
                new ObjectParameter("IDTipoActividad", typeof(long));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actividad_Create", nombreParameter, descripcionParameter, iDTipoActividadParameter, fechaInicioParameter, fechaFinParameter, estadoParameter, iDUsuarioParameter, iDActividad);
        }
    
        public virtual int Actividad_Delete(Nullable<long> iDActividad)
        {
            var iDActividadParameter = iDActividad.HasValue ?
                new ObjectParameter("IDActividad", iDActividad) :
                new ObjectParameter("IDActividad", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actividad_Delete", iDActividadParameter);
        }
    
        public virtual ObjectResult<Actividad_ReadAll_Result> Actividad_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Actividad_ReadAll_Result>("Actividad_ReadAll");
        }
    
        public virtual ObjectResult<Actividad_ReadById_Result> Actividad_ReadById(Nullable<long> iDActividad)
        {
            var iDActividadParameter = iDActividad.HasValue ?
                new ObjectParameter("IDActividad", iDActividad) :
                new ObjectParameter("IDActividad", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Actividad_ReadById_Result>("Actividad_ReadById", iDActividadParameter);
        }
    
        public virtual int Actividad_Update(Nullable<long> iDActividad, string nombre, string descripcion, Nullable<long> iDTipoActividad, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string estado, string iDUsuario)
        {
            var iDActividadParameter = iDActividad.HasValue ?
                new ObjectParameter("IDActividad", iDActividad) :
                new ObjectParameter("IDActividad", typeof(long));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var iDTipoActividadParameter = iDTipoActividad.HasValue ?
                new ObjectParameter("IDTipoActividad", iDTipoActividad) :
                new ObjectParameter("IDTipoActividad", typeof(long));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actividad_Update", iDActividadParameter, nombreParameter, descripcionParameter, iDTipoActividadParameter, fechaInicioParameter, fechaFinParameter, estadoParameter, iDUsuarioParameter);
        }
    
        public virtual int BolsaLaboral_Create(string nombre, string descripcion, string iDUsuario, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string estado, ObjectParameter iDBolsaLaboral)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BolsaLaboral_Create", nombreParameter, descripcionParameter, iDUsuarioParameter, fechaInicioParameter, fechaFinParameter, estadoParameter, iDBolsaLaboral);
        }
    
        public virtual int BolsaLaboral_Delete(Nullable<long> iDBolsaLaboral)
        {
            var iDBolsaLaboralParameter = iDBolsaLaboral.HasValue ?
                new ObjectParameter("IDBolsaLaboral", iDBolsaLaboral) :
                new ObjectParameter("IDBolsaLaboral", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BolsaLaboral_Delete", iDBolsaLaboralParameter);
        }
    
        public virtual ObjectResult<BolsaLaboral_ReadAll_Result> BolsaLaboral_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BolsaLaboral_ReadAll_Result>("BolsaLaboral_ReadAll");
        }
    
        public virtual ObjectResult<BolsaLaboral_ReadById_Result> BolsaLaboral_ReadById(Nullable<long> iDBolsaLaboral)
        {
            var iDBolsaLaboralParameter = iDBolsaLaboral.HasValue ?
                new ObjectParameter("IDBolsaLaboral", iDBolsaLaboral) :
                new ObjectParameter("IDBolsaLaboral", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BolsaLaboral_ReadById_Result>("BolsaLaboral_ReadById", iDBolsaLaboralParameter);
        }
    
        public virtual int BolsaLaboral_Update(Nullable<long> iDBolsaLaboral, string nombre, string descripcion, string iDUsuario, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string estado)
        {
            var iDBolsaLaboralParameter = iDBolsaLaboral.HasValue ?
                new ObjectParameter("IDBolsaLaboral", iDBolsaLaboral) :
                new ObjectParameter("IDBolsaLaboral", typeof(long));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BolsaLaboral_Update", iDBolsaLaboralParameter, nombreParameter, descripcionParameter, iDUsuarioParameter, fechaInicioParameter, fechaFinParameter, estadoParameter);
        }
    
        public virtual int BolsaLaboralCarrera_Create(Nullable<long> iDBolsaLaboral, string iDCarreraProfesional, ObjectParameter iDBolsaLaboralCarrera)
        {
            var iDBolsaLaboralParameter = iDBolsaLaboral.HasValue ?
                new ObjectParameter("IDBolsaLaboral", iDBolsaLaboral) :
                new ObjectParameter("IDBolsaLaboral", typeof(long));
    
            var iDCarreraProfesionalParameter = iDCarreraProfesional != null ?
                new ObjectParameter("IDCarreraProfesional", iDCarreraProfesional) :
                new ObjectParameter("IDCarreraProfesional", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BolsaLaboralCarrera_Create", iDBolsaLaboralParameter, iDCarreraProfesionalParameter, iDBolsaLaboralCarrera);
        }
    
        public virtual int BolsaLaboralCarrera_Delete(Nullable<long> iDBolsaLaboralCarrera)
        {
            var iDBolsaLaboralCarreraParameter = iDBolsaLaboralCarrera.HasValue ?
                new ObjectParameter("IDBolsaLaboralCarrera", iDBolsaLaboralCarrera) :
                new ObjectParameter("IDBolsaLaboralCarrera", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BolsaLaboralCarrera_Delete", iDBolsaLaboralCarreraParameter);
        }
    
        public virtual ObjectResult<BolsaLaboralCarrera_ReadAll_Result> BolsaLaboralCarrera_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BolsaLaboralCarrera_ReadAll_Result>("BolsaLaboralCarrera_ReadAll");
        }
    
        public virtual ObjectResult<BolsaLaboralCarrera_ReadById_Result> BolsaLaboralCarrera_ReadById(Nullable<long> iDBolsaLaboralCarrera)
        {
            var iDBolsaLaboralCarreraParameter = iDBolsaLaboralCarrera.HasValue ?
                new ObjectParameter("IDBolsaLaboralCarrera", iDBolsaLaboralCarrera) :
                new ObjectParameter("IDBolsaLaboralCarrera", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BolsaLaboralCarrera_ReadById_Result>("BolsaLaboralCarrera_ReadById", iDBolsaLaboralCarreraParameter);
        }
    
        public virtual int BolsaLaboralCarrera_Update(Nullable<long> iDBolsaLaboralCarrera, Nullable<long> iDBolsaLaboral, string iDCarreraProfesional)
        {
            var iDBolsaLaboralCarreraParameter = iDBolsaLaboralCarrera.HasValue ?
                new ObjectParameter("IDBolsaLaboralCarrera", iDBolsaLaboralCarrera) :
                new ObjectParameter("IDBolsaLaboralCarrera", typeof(long));
    
            var iDBolsaLaboralParameter = iDBolsaLaboral.HasValue ?
                new ObjectParameter("IDBolsaLaboral", iDBolsaLaboral) :
                new ObjectParameter("IDBolsaLaboral", typeof(long));
    
            var iDCarreraProfesionalParameter = iDCarreraProfesional != null ?
                new ObjectParameter("IDCarreraProfesional", iDCarreraProfesional) :
                new ObjectParameter("IDCarreraProfesional", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BolsaLaboralCarrera_Update", iDBolsaLaboralCarreraParameter, iDBolsaLaboralParameter, iDCarreraProfesionalParameter);
        }
    
        public virtual int Busqueda_Create(string contenido, string iDUsuario, Nullable<System.DateTime> fechaActual, ObjectParameter iDBusqueda)
        {
            var contenidoParameter = contenido != null ?
                new ObjectParameter("Contenido", contenido) :
                new ObjectParameter("Contenido", typeof(string));
    
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            var fechaActualParameter = fechaActual.HasValue ?
                new ObjectParameter("FechaActual", fechaActual) :
                new ObjectParameter("FechaActual", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Busqueda_Create", contenidoParameter, iDUsuarioParameter, fechaActualParameter, iDBusqueda);
        }
    
        public virtual int Busqueda_Delete(Nullable<long> iDBusqueda)
        {
            var iDBusquedaParameter = iDBusqueda.HasValue ?
                new ObjectParameter("IDBusqueda", iDBusqueda) :
                new ObjectParameter("IDBusqueda", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Busqueda_Delete", iDBusquedaParameter);
        }
    
        public virtual ObjectResult<Busqueda_ReadAll_Result> Busqueda_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Busqueda_ReadAll_Result>("Busqueda_ReadAll");
        }
    
        public virtual ObjectResult<Busqueda_ReadById_Result> Busqueda_ReadById(Nullable<long> iDBusqueda)
        {
            var iDBusquedaParameter = iDBusqueda.HasValue ?
                new ObjectParameter("IDBusqueda", iDBusqueda) :
                new ObjectParameter("IDBusqueda", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Busqueda_ReadById_Result>("Busqueda_ReadById", iDBusquedaParameter);
        }
    
        public virtual int Busqueda_Update(Nullable<long> iDBusqueda, string contenido, string iDUsuario, Nullable<System.DateTime> fechaActual)
        {
            var iDBusquedaParameter = iDBusqueda.HasValue ?
                new ObjectParameter("IDBusqueda", iDBusqueda) :
                new ObjectParameter("IDBusqueda", typeof(long));
    
            var contenidoParameter = contenido != null ?
                new ObjectParameter("Contenido", contenido) :
                new ObjectParameter("Contenido", typeof(string));
    
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            var fechaActualParameter = fechaActual.HasValue ?
                new ObjectParameter("FechaActual", fechaActual) :
                new ObjectParameter("FechaActual", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Busqueda_Update", iDBusquedaParameter, contenidoParameter, iDUsuarioParameter, fechaActualParameter);
        }
    
        public virtual int Empresa_Create(string iDEmpresa, string nombreEmpresa, string descripcion)
        {
            var iDEmpresaParameter = iDEmpresa != null ?
                new ObjectParameter("IDEmpresa", iDEmpresa) :
                new ObjectParameter("IDEmpresa", typeof(string));
    
            var nombreEmpresaParameter = nombreEmpresa != null ?
                new ObjectParameter("NombreEmpresa", nombreEmpresa) :
                new ObjectParameter("NombreEmpresa", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Empresa_Create", iDEmpresaParameter, nombreEmpresaParameter, descripcionParameter);
        }
    
        public virtual int Empresa_Delete(string iDEmpresa)
        {
            var iDEmpresaParameter = iDEmpresa != null ?
                new ObjectParameter("IDEmpresa", iDEmpresa) :
                new ObjectParameter("IDEmpresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Empresa_Delete", iDEmpresaParameter);
        }
    
        public virtual ObjectResult<Empresa_ReadAll_Result> Empresa_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresa_ReadAll_Result>("Empresa_ReadAll");
        }
    
        public virtual ObjectResult<Empresa_ReadById_Result> Empresa_ReadById(string iDEmpresa)
        {
            var iDEmpresaParameter = iDEmpresa != null ?
                new ObjectParameter("IDEmpresa", iDEmpresa) :
                new ObjectParameter("IDEmpresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresa_ReadById_Result>("Empresa_ReadById", iDEmpresaParameter);
        }
    
        public virtual int Empresa_Update(string iDEmpresa, string nombreEmpresa, string descripcion)
        {
            var iDEmpresaParameter = iDEmpresa != null ?
                new ObjectParameter("IDEmpresa", iDEmpresa) :
                new ObjectParameter("IDEmpresa", typeof(string));
    
            var nombreEmpresaParameter = nombreEmpresa != null ?
                new ObjectParameter("NombreEmpresa", nombreEmpresa) :
                new ObjectParameter("NombreEmpresa", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Empresa_Update", iDEmpresaParameter, nombreEmpresaParameter, descripcionParameter);
        }
    
        public virtual int EPMiembro_Create(string iDCarreraProfesional, string dNI, ObjectParameter iDCPMiembro)
        {
            var iDCarreraProfesionalParameter = iDCarreraProfesional != null ?
                new ObjectParameter("IDCarreraProfesional", iDCarreraProfesional) :
                new ObjectParameter("IDCarreraProfesional", typeof(string));
    
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EPMiembro_Create", iDCarreraProfesionalParameter, dNIParameter, iDCPMiembro);
        }
    
        public virtual int EPMiembro_Delete(Nullable<long> iDCPMiembro)
        {
            var iDCPMiembroParameter = iDCPMiembro.HasValue ?
                new ObjectParameter("IDCPMiembro", iDCPMiembro) :
                new ObjectParameter("IDCPMiembro", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EPMiembro_Delete", iDCPMiembroParameter);
        }
    
        public virtual ObjectResult<EPMiembro_ReadAll_Result> EPMiembro_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EPMiembro_ReadAll_Result>("EPMiembro_ReadAll");
        }
    
        public virtual ObjectResult<EPMiembro_ReadById_Result> EPMiembro_ReadById(Nullable<long> iDCPMiembro)
        {
            var iDCPMiembroParameter = iDCPMiembro.HasValue ?
                new ObjectParameter("IDCPMiembro", iDCPMiembro) :
                new ObjectParameter("IDCPMiembro", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EPMiembro_ReadById_Result>("EPMiembro_ReadById", iDCPMiembroParameter);
        }
    
        public virtual int EPMiembro_Update(Nullable<long> iDCPMiembro, string iDCarreraProfesional, string dNI)
        {
            var iDCPMiembroParameter = iDCPMiembro.HasValue ?
                new ObjectParameter("IDCPMiembro", iDCPMiembro) :
                new ObjectParameter("IDCPMiembro", typeof(long));
    
            var iDCarreraProfesionalParameter = iDCarreraProfesional != null ?
                new ObjectParameter("IDCarreraProfesional", iDCarreraProfesional) :
                new ObjectParameter("IDCarreraProfesional", typeof(string));
    
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EPMiembro_Update", iDCPMiembroParameter, iDCarreraProfesionalParameter, dNIParameter);
        }
    
        public virtual int EscuelaProfesional_Create(string iDCarreraProfesional, string nombre, string descripcion)
        {
            var iDCarreraProfesionalParameter = iDCarreraProfesional != null ?
                new ObjectParameter("IDCarreraProfesional", iDCarreraProfesional) :
                new ObjectParameter("IDCarreraProfesional", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EscuelaProfesional_Create", iDCarreraProfesionalParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int EscuelaProfesional_Delete(string iDCarreraProfesional)
        {
            var iDCarreraProfesionalParameter = iDCarreraProfesional != null ?
                new ObjectParameter("IDCarreraProfesional", iDCarreraProfesional) :
                new ObjectParameter("IDCarreraProfesional", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EscuelaProfesional_Delete", iDCarreraProfesionalParameter);
        }
    
        public virtual ObjectResult<EscuelaProfesional_ReadAll_Result> EscuelaProfesional_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EscuelaProfesional_ReadAll_Result>("EscuelaProfesional_ReadAll");
        }
    
        public virtual ObjectResult<EscuelaProfesional_ReadById_Result> EscuelaProfesional_ReadById(string iDCarreraProfesional)
        {
            var iDCarreraProfesionalParameter = iDCarreraProfesional != null ?
                new ObjectParameter("IDCarreraProfesional", iDCarreraProfesional) :
                new ObjectParameter("IDCarreraProfesional", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EscuelaProfesional_ReadById_Result>("EscuelaProfesional_ReadById", iDCarreraProfesionalParameter);
        }
    
        public virtual int EscuelaProfesional_Update(string iDCarreraProfesional, string nombre, string descripcion)
        {
            var iDCarreraProfesionalParameter = iDCarreraProfesional != null ?
                new ObjectParameter("IDCarreraProfesional", iDCarreraProfesional) :
                new ObjectParameter("IDCarreraProfesional", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EscuelaProfesional_Update", iDCarreraProfesionalParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int Membresia_Create(string iDAsociado, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string tipo, string categoriaMembresia, string estado, ObjectParameter iDMembresia)
        {
            var iDAsociadoParameter = iDAsociado != null ?
                new ObjectParameter("IDAsociado", iDAsociado) :
                new ObjectParameter("IDAsociado", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var categoriaMembresiaParameter = categoriaMembresia != null ?
                new ObjectParameter("CategoriaMembresia", categoriaMembresia) :
                new ObjectParameter("CategoriaMembresia", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Membresia_Create", iDAsociadoParameter, fechaInicioParameter, fechaFinParameter, tipoParameter, categoriaMembresiaParameter, estadoParameter, iDMembresia);
        }
    
        public virtual int Membresia_Delete(Nullable<long> iDMembresia)
        {
            var iDMembresiaParameter = iDMembresia.HasValue ?
                new ObjectParameter("IDMembresia", iDMembresia) :
                new ObjectParameter("IDMembresia", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Membresia_Delete", iDMembresiaParameter);
        }
    
        public virtual ObjectResult<Membresia_ReadAll_Result> Membresia_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Membresia_ReadAll_Result>("Membresia_ReadAll");
        }
    
        public virtual ObjectResult<Membresia_ReadById_Result> Membresia_ReadById(Nullable<long> iDMembresia)
        {
            var iDMembresiaParameter = iDMembresia.HasValue ?
                new ObjectParameter("IDMembresia", iDMembresia) :
                new ObjectParameter("IDMembresia", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Membresia_ReadById_Result>("Membresia_ReadById", iDMembresiaParameter);
        }
    
        public virtual int Membresia_Update(Nullable<long> iDMembresia, string iDAsociado, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string tipo, string categoriaMembresia, string estado)
        {
            var iDMembresiaParameter = iDMembresia.HasValue ?
                new ObjectParameter("IDMembresia", iDMembresia) :
                new ObjectParameter("IDMembresia", typeof(long));
    
            var iDAsociadoParameter = iDAsociado != null ?
                new ObjectParameter("IDAsociado", iDAsociado) :
                new ObjectParameter("IDAsociado", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var categoriaMembresiaParameter = categoriaMembresia != null ?
                new ObjectParameter("CategoriaMembresia", categoriaMembresia) :
                new ObjectParameter("CategoriaMembresia", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Membresia_Update", iDMembresiaParameter, iDAsociadoParameter, fechaInicioParameter, fechaFinParameter, tipoParameter, categoriaMembresiaParameter, estadoParameter);
        }
    
        public virtual int Miembro_Create(string dNI, string apellidoPaterno, string apellidoMaterno, string nombres, string celular, string telefonopcional, string direccion, string correoElectronico)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("ApellidoPaterno", apellidoPaterno) :
                new ObjectParameter("ApellidoPaterno", typeof(string));
    
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("ApellidoMaterno", apellidoMaterno) :
                new ObjectParameter("ApellidoMaterno", typeof(string));
    
            var nombresParameter = nombres != null ?
                new ObjectParameter("Nombres", nombres) :
                new ObjectParameter("Nombres", typeof(string));
    
            var celularParameter = celular != null ?
                new ObjectParameter("Celular", celular) :
                new ObjectParameter("Celular", typeof(string));
    
            var telefonopcionalParameter = telefonopcional != null ?
                new ObjectParameter("Telefonopcional", telefonopcional) :
                new ObjectParameter("Telefonopcional", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Miembro_Create", dNIParameter, apellidoPaternoParameter, apellidoMaternoParameter, nombresParameter, celularParameter, telefonopcionalParameter, direccionParameter, correoElectronicoParameter);
        }
    
        public virtual int Miembro_Delete(string dNI)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Miembro_Delete", dNIParameter);
        }
    
        public virtual ObjectResult<Miembro_ReadAll_Result> Miembro_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Miembro_ReadAll_Result>("Miembro_ReadAll");
        }
    
        public virtual ObjectResult<Miembro_ReadById_Result> Miembro_ReadById(string dNI)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Miembro_ReadById_Result>("Miembro_ReadById", dNIParameter);
        }
    
        public virtual int Miembro_Update(string dNI, string apellidoPaterno, string apellidoMaterno, string nombres, string celular, string telefonopcional, string direccion, string correoElectronico)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("ApellidoPaterno", apellidoPaterno) :
                new ObjectParameter("ApellidoPaterno", typeof(string));
    
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("ApellidoMaterno", apellidoMaterno) :
                new ObjectParameter("ApellidoMaterno", typeof(string));
    
            var nombresParameter = nombres != null ?
                new ObjectParameter("Nombres", nombres) :
                new ObjectParameter("Nombres", typeof(string));
    
            var celularParameter = celular != null ?
                new ObjectParameter("Celular", celular) :
                new ObjectParameter("Celular", typeof(string));
    
            var telefonopcionalParameter = telefonopcional != null ?
                new ObjectParameter("Telefonopcional", telefonopcional) :
                new ObjectParameter("Telefonopcional", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Miembro_Update", dNIParameter, apellidoPaternoParameter, apellidoMaternoParameter, nombresParameter, celularParameter, telefonopcionalParameter, direccionParameter, correoElectronicoParameter);
        }
    
        public virtual int Notificacion_Create(string iDUsuario, Nullable<System.DateTime> fechaNotificacion, string textoNotificacion, Nullable<long> iDPublicacion, ObjectParameter iDNotificacion)
        {
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            var fechaNotificacionParameter = fechaNotificacion.HasValue ?
                new ObjectParameter("FechaNotificacion", fechaNotificacion) :
                new ObjectParameter("FechaNotificacion", typeof(System.DateTime));
    
            var textoNotificacionParameter = textoNotificacion != null ?
                new ObjectParameter("TextoNotificacion", textoNotificacion) :
                new ObjectParameter("TextoNotificacion", typeof(string));
    
            var iDPublicacionParameter = iDPublicacion.HasValue ?
                new ObjectParameter("IDPublicacion", iDPublicacion) :
                new ObjectParameter("IDPublicacion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Notificacion_Create", iDUsuarioParameter, fechaNotificacionParameter, textoNotificacionParameter, iDPublicacionParameter, iDNotificacion);
        }
    
        public virtual int Notificacion_Delete(Nullable<long> iDNotificacion)
        {
            var iDNotificacionParameter = iDNotificacion.HasValue ?
                new ObjectParameter("IDNotificacion", iDNotificacion) :
                new ObjectParameter("IDNotificacion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Notificacion_Delete", iDNotificacionParameter);
        }
    
        public virtual ObjectResult<Notificacion_ReadAll_Result> Notificacion_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Notificacion_ReadAll_Result>("Notificacion_ReadAll");
        }
    
        public virtual ObjectResult<Notificacion_ReadById_Result> Notificacion_ReadById(Nullable<long> iDNotificacion)
        {
            var iDNotificacionParameter = iDNotificacion.HasValue ?
                new ObjectParameter("IDNotificacion", iDNotificacion) :
                new ObjectParameter("IDNotificacion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Notificacion_ReadById_Result>("Notificacion_ReadById", iDNotificacionParameter);
        }
    
        public virtual int Notificacion_Update(Nullable<long> iDNotificacion, string iDUsuario, Nullable<System.DateTime> fechaNotificacion, string textoNotificacion, Nullable<long> iDPublicacion)
        {
            var iDNotificacionParameter = iDNotificacion.HasValue ?
                new ObjectParameter("IDNotificacion", iDNotificacion) :
                new ObjectParameter("IDNotificacion", typeof(long));
    
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            var fechaNotificacionParameter = fechaNotificacion.HasValue ?
                new ObjectParameter("FechaNotificacion", fechaNotificacion) :
                new ObjectParameter("FechaNotificacion", typeof(System.DateTime));
    
            var textoNotificacionParameter = textoNotificacion != null ?
                new ObjectParameter("TextoNotificacion", textoNotificacion) :
                new ObjectParameter("TextoNotificacion", typeof(string));
    
            var iDPublicacionParameter = iDPublicacion.HasValue ?
                new ObjectParameter("IDPublicacion", iDPublicacion) :
                new ObjectParameter("IDPublicacion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Notificacion_Update", iDNotificacionParameter, iDUsuarioParameter, fechaNotificacionParameter, textoNotificacionParameter, iDPublicacionParameter);
        }
    
        public virtual int Promocion_Create(string nombre, string descripcion, string iDUsuario, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string estado, string codigoPromo, ObjectParameter iDPromocion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var codigoPromoParameter = codigoPromo != null ?
                new ObjectParameter("CodigoPromo", codigoPromo) :
                new ObjectParameter("CodigoPromo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Promocion_Create", nombreParameter, descripcionParameter, iDUsuarioParameter, fechaInicioParameter, fechaFinParameter, estadoParameter, codigoPromoParameter, iDPromocion);
        }
    
        public virtual int Promocion_Delete(Nullable<long> iDPromocion)
        {
            var iDPromocionParameter = iDPromocion.HasValue ?
                new ObjectParameter("IDPromocion", iDPromocion) :
                new ObjectParameter("IDPromocion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Promocion_Delete", iDPromocionParameter);
        }
    
        public virtual ObjectResult<Promocion_ReadAll_Result> Promocion_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Promocion_ReadAll_Result>("Promocion_ReadAll");
        }
    
        public virtual ObjectResult<Promocion_ReadById_Result> Promocion_ReadById(Nullable<long> iDPromocion)
        {
            var iDPromocionParameter = iDPromocion.HasValue ?
                new ObjectParameter("IDPromocion", iDPromocion) :
                new ObjectParameter("IDPromocion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Promocion_ReadById_Result>("Promocion_ReadById", iDPromocionParameter);
        }
    
        public virtual int Promocion_Update(Nullable<long> iDPromocion, string nombre, string descripcion, string iDUsuario, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string estado, string codigoPromo)
        {
            var iDPromocionParameter = iDPromocion.HasValue ?
                new ObjectParameter("IDPromocion", iDPromocion) :
                new ObjectParameter("IDPromocion", typeof(long));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var codigoPromoParameter = codigoPromo != null ?
                new ObjectParameter("CodigoPromo", codigoPromo) :
                new ObjectParameter("CodigoPromo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Promocion_Update", iDPromocionParameter, nombreParameter, descripcionParameter, iDUsuarioParameter, fechaInicioParameter, fechaFinParameter, estadoParameter, codigoPromoParameter);
        }
    
        public virtual int Publicacion_Create(Nullable<long> iDPromocion, Nullable<long> iDBolsaLaboral, Nullable<long> iDActividad, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string estado, ObjectParameter iDPublicacion)
        {
            var iDPromocionParameter = iDPromocion.HasValue ?
                new ObjectParameter("IDPromocion", iDPromocion) :
                new ObjectParameter("IDPromocion", typeof(long));
    
            var iDBolsaLaboralParameter = iDBolsaLaboral.HasValue ?
                new ObjectParameter("IDBolsaLaboral", iDBolsaLaboral) :
                new ObjectParameter("IDBolsaLaboral", typeof(long));
    
            var iDActividadParameter = iDActividad.HasValue ?
                new ObjectParameter("IDActividad", iDActividad) :
                new ObjectParameter("IDActividad", typeof(long));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Publicacion_Create", iDPromocionParameter, iDBolsaLaboralParameter, iDActividadParameter, fechaInicioParameter, fechaFinParameter, estadoParameter, iDPublicacion);
        }
    
        public virtual int Publicacion_Delete(Nullable<long> iDPublicacion)
        {
            var iDPublicacionParameter = iDPublicacion.HasValue ?
                new ObjectParameter("IDPublicacion", iDPublicacion) :
                new ObjectParameter("IDPublicacion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Publicacion_Delete", iDPublicacionParameter);
        }
    
        public virtual ObjectResult<Publicacion_ReadAll_Result> Publicacion_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Publicacion_ReadAll_Result>("Publicacion_ReadAll");
        }
    
        public virtual ObjectResult<Publicacion_ReadById_Result> Publicacion_ReadById(Nullable<long> iDPublicacion)
        {
            var iDPublicacionParameter = iDPublicacion.HasValue ?
                new ObjectParameter("IDPublicacion", iDPublicacion) :
                new ObjectParameter("IDPublicacion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Publicacion_ReadById_Result>("Publicacion_ReadById", iDPublicacionParameter);
        }
    
        public virtual int Publicacion_Update(Nullable<long> iDPublicacion, Nullable<long> iDPromocion, Nullable<long> iDBolsaLaboral, Nullable<long> iDActividad, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string estado)
        {
            var iDPublicacionParameter = iDPublicacion.HasValue ?
                new ObjectParameter("IDPublicacion", iDPublicacion) :
                new ObjectParameter("IDPublicacion", typeof(long));
    
            var iDPromocionParameter = iDPromocion.HasValue ?
                new ObjectParameter("IDPromocion", iDPromocion) :
                new ObjectParameter("IDPromocion", typeof(long));
    
            var iDBolsaLaboralParameter = iDBolsaLaboral.HasValue ?
                new ObjectParameter("IDBolsaLaboral", iDBolsaLaboral) :
                new ObjectParameter("IDBolsaLaboral", typeof(long));
    
            var iDActividadParameter = iDActividad.HasValue ?
                new ObjectParameter("IDActividad", iDActividad) :
                new ObjectParameter("IDActividad", typeof(long));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Publicacion_Update", iDPublicacionParameter, iDPromocionParameter, iDBolsaLaboralParameter, iDActividadParameter, fechaInicioParameter, fechaFinParameter, estadoParameter);
        }
    
        public virtual int Sesion_Create(string iDUsuario, Nullable<System.TimeSpan> duracion, Nullable<System.DateTime> fechaIngreso, Nullable<System.DateTime> fechaFin, ObjectParameter iDSesion)
        {
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            var duracionParameter = duracion.HasValue ?
                new ObjectParameter("Duracion", duracion) :
                new ObjectParameter("Duracion", typeof(System.TimeSpan));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("FechaIngreso", fechaIngreso) :
                new ObjectParameter("FechaIngreso", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sesion_Create", iDUsuarioParameter, duracionParameter, fechaIngresoParameter, fechaFinParameter, iDSesion);
        }
    
        public virtual int Sesion_Delete(Nullable<long> iDSesion)
        {
            var iDSesionParameter = iDSesion.HasValue ?
                new ObjectParameter("IDSesion", iDSesion) :
                new ObjectParameter("IDSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sesion_Delete", iDSesionParameter);
        }
    
        public virtual ObjectResult<Sesion_ReadAll_Result> Sesion_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sesion_ReadAll_Result>("Sesion_ReadAll");
        }
    
        public virtual ObjectResult<Sesion_ReadById_Result> Sesion_ReadById(Nullable<long> iDSesion)
        {
            var iDSesionParameter = iDSesion.HasValue ?
                new ObjectParameter("IDSesion", iDSesion) :
                new ObjectParameter("IDSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sesion_ReadById_Result>("Sesion_ReadById", iDSesionParameter);
        }
    
        public virtual int Sesion_Update(Nullable<long> iDSesion, string iDUsuario, Nullable<System.TimeSpan> duracion, Nullable<System.DateTime> fechaIngreso, Nullable<System.DateTime> fechaFin)
        {
            var iDSesionParameter = iDSesion.HasValue ?
                new ObjectParameter("IDSesion", iDSesion) :
                new ObjectParameter("IDSesion", typeof(long));
    
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            var duracionParameter = duracion.HasValue ?
                new ObjectParameter("Duracion", duracion) :
                new ObjectParameter("Duracion", typeof(System.TimeSpan));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("FechaIngreso", fechaIngreso) :
                new ObjectParameter("FechaIngreso", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sesion_Update", iDSesionParameter, iDUsuarioParameter, duracionParameter, fechaIngresoParameter, fechaFinParameter);
        }
    
        public virtual int Solicitud_Create(string nombres, string apellidos, string telefono, string correo, string tipoRequerimiento, string descripcion, Nullable<System.DateTime> fecha, string estado, ObjectParameter iDSolicitud)
        {
            var nombresParameter = nombres != null ?
                new ObjectParameter("Nombres", nombres) :
                new ObjectParameter("Nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var tipoRequerimientoParameter = tipoRequerimiento != null ?
                new ObjectParameter("TipoRequerimiento", tipoRequerimiento) :
                new ObjectParameter("TipoRequerimiento", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Solicitud_Create", nombresParameter, apellidosParameter, telefonoParameter, correoParameter, tipoRequerimientoParameter, descripcionParameter, fechaParameter, estadoParameter, iDSolicitud);
        }
    
        public virtual int Solicitud_Delete(Nullable<long> iDSolicitud)
        {
            var iDSolicitudParameter = iDSolicitud.HasValue ?
                new ObjectParameter("IDSolicitud", iDSolicitud) :
                new ObjectParameter("IDSolicitud", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Solicitud_Delete", iDSolicitudParameter);
        }
    
        public virtual ObjectResult<Solicitud_ReadAll_Result> Solicitud_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Solicitud_ReadAll_Result>("Solicitud_ReadAll");
        }
    
        public virtual ObjectResult<Solicitud_ReadById_Result> Solicitud_ReadById(Nullable<long> iDSolicitud)
        {
            var iDSolicitudParameter = iDSolicitud.HasValue ?
                new ObjectParameter("IDSolicitud", iDSolicitud) :
                new ObjectParameter("IDSolicitud", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Solicitud_ReadById_Result>("Solicitud_ReadById", iDSolicitudParameter);
        }
    
        public virtual int Solicitud_Update(Nullable<long> iDSolicitud, string nombres, string apellidos, string telefono, string correo, string tipoRequerimiento, string descripcion, Nullable<System.DateTime> fecha, string estado)
        {
            var iDSolicitudParameter = iDSolicitud.HasValue ?
                new ObjectParameter("IDSolicitud", iDSolicitud) :
                new ObjectParameter("IDSolicitud", typeof(long));
    
            var nombresParameter = nombres != null ?
                new ObjectParameter("Nombres", nombres) :
                new ObjectParameter("Nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var tipoRequerimientoParameter = tipoRequerimiento != null ?
                new ObjectParameter("TipoRequerimiento", tipoRequerimiento) :
                new ObjectParameter("TipoRequerimiento", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Solicitud_Update", iDSolicitudParameter, nombresParameter, apellidosParameter, telefonoParameter, correoParameter, tipoRequerimientoParameter, descripcionParameter, fechaParameter, estadoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sysdiagrams_Delete(Nullable<int> diagram_id)
        {
            var diagram_idParameter = diagram_id.HasValue ?
                new ObjectParameter("diagram_id", diagram_id) :
                new ObjectParameter("diagram_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sysdiagrams_Delete", diagram_idParameter);
        }
    
        public virtual ObjectResult<sysdiagrams_ReadAll_Result> sysdiagrams_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sysdiagrams_ReadAll_Result>("sysdiagrams_ReadAll");
        }
    
        public virtual ObjectResult<sysdiagrams_ReadById_Result> sysdiagrams_ReadById(Nullable<int> diagram_id)
        {
            var diagram_idParameter = diagram_id.HasValue ?
                new ObjectParameter("diagram_id", diagram_id) :
                new ObjectParameter("diagram_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sysdiagrams_ReadById_Result>("sysdiagrams_ReadById", diagram_idParameter);
        }
    
        public virtual int Tag_Create(string palabra, ObjectParameter iDTag)
        {
            var palabraParameter = palabra != null ?
                new ObjectParameter("Palabra", palabra) :
                new ObjectParameter("Palabra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tag_Create", palabraParameter, iDTag);
        }
    
        public virtual int Tag_Delete(Nullable<long> iDTag)
        {
            var iDTagParameter = iDTag.HasValue ?
                new ObjectParameter("IDTag", iDTag) :
                new ObjectParameter("IDTag", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tag_Delete", iDTagParameter);
        }
    
        public virtual ObjectResult<Tag_ReadAll_Result> Tag_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tag_ReadAll_Result>("Tag_ReadAll");
        }
    
        public virtual ObjectResult<Tag_ReadById_Result> Tag_ReadById(Nullable<long> iDTag)
        {
            var iDTagParameter = iDTag.HasValue ?
                new ObjectParameter("IDTag", iDTag) :
                new ObjectParameter("IDTag", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tag_ReadById_Result>("Tag_ReadById", iDTagParameter);
        }
    
        public virtual int Tag_Update(Nullable<long> iDTag, string palabra)
        {
            var iDTagParameter = iDTag.HasValue ?
                new ObjectParameter("IDTag", iDTag) :
                new ObjectParameter("IDTag", typeof(long));
    
            var palabraParameter = palabra != null ?
                new ObjectParameter("Palabra", palabra) :
                new ObjectParameter("Palabra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tag_Update", iDTagParameter, palabraParameter);
        }
    
        public virtual int TipoActividad_Create(string nombre, ObjectParameter iDTipoActividad)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TipoActividad_Create", nombreParameter, iDTipoActividad);
        }
    
        public virtual int TipoActividad_Delete(Nullable<long> iDTipoActividad)
        {
            var iDTipoActividadParameter = iDTipoActividad.HasValue ?
                new ObjectParameter("IDTipoActividad", iDTipoActividad) :
                new ObjectParameter("IDTipoActividad", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TipoActividad_Delete", iDTipoActividadParameter);
        }
    
        public virtual ObjectResult<TipoActividad_ReadAll_Result> TipoActividad_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TipoActividad_ReadAll_Result>("TipoActividad_ReadAll");
        }
    
        public virtual ObjectResult<TipoActividad_ReadById_Result> TipoActividad_ReadById(Nullable<long> iDTipoActividad)
        {
            var iDTipoActividadParameter = iDTipoActividad.HasValue ?
                new ObjectParameter("IDTipoActividad", iDTipoActividad) :
                new ObjectParameter("IDTipoActividad", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TipoActividad_ReadById_Result>("TipoActividad_ReadById", iDTipoActividadParameter);
        }
    
        public virtual int TipoActividad_Update(Nullable<long> iDTipoActividad, string nombre)
        {
            var iDTipoActividadParameter = iDTipoActividad.HasValue ?
                new ObjectParameter("IDTipoActividad", iDTipoActividad) :
                new ObjectParameter("IDTipoActividad", typeof(long));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TipoActividad_Update", iDTipoActividadParameter, nombreParameter);
        }
    
        public virtual int Usuario_Create(string iDUsuario, string contraseña, string estado, string iDAsociado, Nullable<long> iDMembresia, string permiso)
        {
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var iDAsociadoParameter = iDAsociado != null ?
                new ObjectParameter("IDAsociado", iDAsociado) :
                new ObjectParameter("IDAsociado", typeof(string));
    
            var iDMembresiaParameter = iDMembresia.HasValue ?
                new ObjectParameter("IDMembresia", iDMembresia) :
                new ObjectParameter("IDMembresia", typeof(long));
    
            var permisoParameter = permiso != null ?
                new ObjectParameter("Permiso", permiso) :
                new ObjectParameter("Permiso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usuario_Create", iDUsuarioParameter, contraseñaParameter, estadoParameter, iDAsociadoParameter, iDMembresiaParameter, permisoParameter);
        }
    
        public virtual int Usuario_Delete(string iDUsuario)
        {
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usuario_Delete", iDUsuarioParameter);
        }
    
        public virtual ObjectResult<Usuario_ReadAll_Result> Usuario_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario_ReadAll_Result>("Usuario_ReadAll");
        }
    
        public virtual ObjectResult<Usuario_ReadById_Result> Usuario_ReadById(string iDUsuario)
        {
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario_ReadById_Result>("Usuario_ReadById", iDUsuarioParameter);
        }
    
        public virtual int Usuario_Update(string iDUsuario, string contraseña, string estado, string iDAsociado, Nullable<long> iDMembresia, string permiso)
        {
            var iDUsuarioParameter = iDUsuario != null ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var iDAsociadoParameter = iDAsociado != null ?
                new ObjectParameter("IDAsociado", iDAsociado) :
                new ObjectParameter("IDAsociado", typeof(string));
    
            var iDMembresiaParameter = iDMembresia.HasValue ?
                new ObjectParameter("IDMembresia", iDMembresia) :
                new ObjectParameter("IDMembresia", typeof(long));
    
            var permisoParameter = permiso != null ?
                new ObjectParameter("Permiso", permiso) :
                new ObjectParameter("Permiso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usuario_Update", iDUsuarioParameter, contraseñaParameter, estadoParameter, iDAsociadoParameter, iDMembresiaParameter, permisoParameter);
        }
    }
}
