//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUGUACSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocion
    {
        public Promocion()
        {
            this.Publicacion = new HashSet<Publicacion>();
        }
    
        public long IDPromocion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string IDUsuario { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Estado { get; set; }
        public string CodigoPromo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Publicacion> Publicacion { get; set; }
    }
}
