//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUGUACSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public Publicacion()
        {
            this.Notificacion = new HashSet<Notificacion>();
        }
    
        public long IDPublicacion { get; set; }
        public Nullable<long> IDPromocion { get; set; }
        public Nullable<long> IDBolsaLaboral { get; set; }
        public Nullable<long> IDActividad { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Estado { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual BolsaLaboral BolsaLaboral { get; set; }
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        public virtual Promocion Promocion { get; set; }
    }
}
