//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUGUACSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesion
    {
        public long IDSesion { get; set; }
        public string IDUsuario { get; set; }
        public Nullable<System.TimeSpan> Duracion { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
